* Summary

This repository contains machine learning programs that can be used to predict the radial distribution function (RDF), pressure, and residual internal energy of a Lennard-Jones fluid. 

The program Generate_RDF_using_LR-RDF.py uses the data from RDF_Data.zip to determine the LJ RDF. 

The program Generate_Pressure_and_InternalEnergy_using_KRR.py uses the data from Gottschalk_Data.zip to determine the pressure and internal energy.

* Installation

In order to use both programs, unzip the corresponding dataset (RDF_Data.zip or Gottschalk_Data.zip) into the same directory as the respective Python program and then execute the program.

* Citations

The relevant citations for these programs and the RDF dataset are:

 - G. T. Craven, "Machine learning codes for structural and thermodynamic properties of a Lennard-Jones fluid", (2020)
  
 - G. T. Craven, "Lennard-Jones radial distribution function dataset", (2020)
  
 - G. T. Craven, N. Lubbers, K. Barros, and S. Tretiak, J. Chem. Phys. 153, XXXX (2020)
  
 - G. T. Craven, N. Lubbers, K. Barros, and S. Tretiak, J. Phys. Chem. Lett. 11, 4372–4378 (2020)
